### PR TITLE
Added Commitizen to repo.  

### PR DESCRIPTION
**Pull request by chalettu**
Added instructions for how people can go about using commitizen for consistent git messages and
release messaging.

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label enhancement

**Comment by chriskacerguis** [comment]
So how does commitizen help?

**Comment by chalettu** [comment]
It is basically a simple little guided tool that enforces a standard on commit messages for code to the repo.  Where this helps is that semantic version uses this consistent format for commit messages to form the release documentation on github.  https://github.com/ManageIQ/manageiq-api-mock/releases has an example of what the auto generated documentation looks like.  It's not the end of the world if we don't use it but I do like that it creates a clean changelog when we are adding things

**Comment by chriskacerguis** [comment]
Not really sold on Commitizen.  It's an optional thing, with no real way to enforce; other than PR reviews...which if that is our only way, I'd rather just do a .github PR template (see: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository)

**Comment by chriskacerguis** [comment]
Not saying "No" by any stretch of the imagination...just trying to understand what we gain by adding a new dependency.

**Comment by chalettu** [comment]
Well PR templates will make for the PR content being standardized, but this
is merely to have cleaner commit messages and autogenerated changelog for
releases.  Other big projects like Angular use this to help auto document
releases in GH.  It is more of a convenience/style thing than anything
else.

**Comment by chriskacerguis** [comment]
ok, makes sense.

**Pull request merged**
